### ISSUE TITLE
Cannot run simulator on windows

### ISSUE THREAD

**Issue by Xyfuture** [SpinalHDL/SpinalTemplateSbt#12]
I am a windows 10 user and want to learn spinal hdl. I follow instructions in SpinalHDL doc and open this project with IDEA. I installed verilator in msys2 and run all the commands as the doc suggested. When I run "MyTopLevelSim.scala" for the first time with clion, I got test.vcd successfully. But when I click the run button again, errors occured. It told me cc1plus.exe doesn't exist, but actually I can find the program by the path that it told me. 
I tried many ways to sovle this problem. I find that if I delete the file "VMyTopLevel__spinalWrapper.cpp" , I can get the wave file again. So I think it's maybe something wrong either in my computer or this porject.
Here is the build info 
![image](https://user-images.githubusercontent.com/49277529/136412899-66067a89-fcef-4d4b-be49-b61922a4684a.png)
I can find the file by manual
![image](https://user-images.githubusercontent.com/49277529/136413182-2defad1c-8513-47f7-8cc7-5a67678a75d8.png)

**Comment by numero-744** [comment]
I think this issue can be closed
