### ISSUE TITLE
SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX Unmapped relationship: 7 Error in WIndows 11

### ISSUE THREAD

**Issue by surabibio** [SpinalHDL/SpinalTemplateSbt#15]
This is the error I get in windows 11
On windows 10 it works well.

[info] [Progress] at 0.641 : Elaborate components
[error] Exception in thread "main" java.lang.IllegalStateException: Unmapped relationship: 7
[error]         at com.sun.jna.platform.win32.WinNT$SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX.fromPointer(WinNT.java:2999)
[error]         at com.sun.jna.platform.win32.Kernel32Util.getLogicalProcessorInformationEx(Kernel32Util.java:715)
[error]         at oshi.hardware.platform.windows.WindowsCentralProcessor.getLogicalProcessorInformationEx(WindowsCentralProcessor.java:168
[error]         at oshi.hardware.platform.windows.WindowsCentralProcessor.initProcessorCounts(WindowsCentralProcessor.java:158)
[error]         at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:73)
[error]         at oshi.hardware.platform.windows.WindowsCentralProcessor.<init>(WindowsCentralProcessor.java:77)
[error]         at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.createProcessor(WindowsHardwareAbstractionLayer.java:60)
[error]         at oshi.util.Memoizer$1.get(Memoizer.java:87)
[error]         at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:66)
[error]         at spinal.sim.SimManager$.liftedTree1$1(SimManager.scala:73)
[error]         at spinal.sim.SimManager$.cpuCount$lzycompute(SimManager.scala:71)
[error]         at spinal.sim.SimManager$.cpuCount(SimManager.scala:70)
[error]         at spinal.sim.SimManager$.newCpuAffinity(SimManager.scala:83)

**Comment by eMApen** [comment]
Same question.
I've found out the old version is working well on windows 11.

sbt.version=1.4.7
ThisBuild / scalaVersion := "2.11.12"
val spinalVersion = "1.6.4"

**Comment by numero-744** [comment]
@surabibio @eMApen is it okay for you? Can be close this issue?

**Comment by surabibio** [comment]
Sure. I think it works fine in win11 now.
