### ISSUE TITLE
Can not find Spinal v1.7.3 under scala v2.12.16

### ISSUE THREAD

**Issue by tanhongze** [SpinalHDL/SpinalTemplateSbt#19]
In build.sbt:
`ThisBuild / scalaVersion := "2.12.16"`
However, Spinal v1.7.3 for scala 2.12.16 is not published. 
So, change it to `ThisBuild / scalaVersion := "2.13.8"` ?

**Comment by Dolu1990** [comment]
Hi, Maybe it was too early to try ?
I mean, now it works for me.

https://oss.sonatype.org/content/groups/public/com/github/spinalhdl/spinalhdl-core_2.12/1.7.3/
