### ISSUE TITLE
While the repository of "sbt.pgp" has been renamed to "com.github.sbt", compile would fail.

### ISSUE THREAD

**Issue by Readon** [SpinalHDL/SpinalTemplateSbt#20]
If the sbt is not installed by coursier, this project would compile fail. 
Reported on SpinalHDL/SpinalHDL#922

It might be done by a failover mechanism.
If install from "com.jsuereth" fails, then install from "com.github.sbt".

**Comment by numero-744** [comment]
I think it has been fixed so this issue can be closed?
