### ISSUE TITLE
scala file path

### ISSUE THREAD

**Issue by jiejie324** [SpinalHDL/SpinalTemplateSbt#9]
why the scala file path must be src/main/scala/mylib/xxx.scala？Is there a way to put it under another path？？

**Comment by typingArtist** [comment]
That’s mostly convention. ```src/main/scala``` is the shortest path for Scala stuff in sbt. If you create multiple sbt projects in your repository, you end up having ```<project>/src/main/scala``` as the path for the Scala stuff.
If you have source files in other languages, they go into different directories, like ```src/main/java```. If you support multiple versions of Scala and need different code for each version, you could have ```src/main/scala2.11``` and ```src/main/scala2.12```. If you add tests, they go to ```src/test/scala```.

Below the Scala directory, it is your choice how you organize the source code. However, again convention kicks in that suggests that you put stuff that is part of ```package mylib``` into a directory called ```mylib``` below the Scala base directory. If you scatter your library more, you would typically create not only multiple source files but also multiple directories below the ```mylib``` folder.

If you want to change the path of the project, you can change it in ```build.sbt```. Or you can change from sbt to the Mill build tool, which supports different or even custom directory structures.

**Comment by typingArtist** [comment]
You can review the [sbt docs](https://www.scala-sbt.org/1.x/docs/Directories.html) about the directory structure.

Mill also documents its [simplified directory structure](https://com-lihaoyi.github.io/mill/mill/Intro_to_Mill.html#_getting_started), however you can use the [sbt structure](https://com-lihaoyi.github.io/mill/mill/Common_Project_Layouts.html#_sbt_compatible_modules) or [change it if needed](https://com-lihaoyi.github.io/mill/mill/Modules.html#_millsourcepath).

**Comment by numero-744** [comment]
The answer is interesting, maybe it could be added to RTD?

**Comment by Dolu1990** [comment]
sure ^^

**Comment by numero-744** [comment]
I think this can be closed now
